M48
; DRILL file {KiCad (6.0.11)} date Mon Mar 20 13:43:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-20T13:43:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1378
%
G90
G05
T1
X4.5745Y-2.8344
X4.7655Y-2.8344
T2
X4.5627Y-2.7151
X4.7773Y-2.7151
T3
X2.07Y-3.8725
T0
M30
